services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: moodle
      POSTGRES_USER: moodle
      POSTGRES_DB: moodle
    volumes:
      - postgres_data:/var/lib/postgresql/data

  moodle:
    image: erseco/alpine-moodle
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_TYPE: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle

      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: "AdminFort3!"
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITENAME: "Moodle en Docker"
      MOODLE_LANGUAGE: es
      SITE_URL: http://localhost:8080

    ports:
      - "8080:8080"

    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html

volumes:
  postgres_data:
  moodledata:
  moodlehtml:
